name: build-and-deploy-api

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  RESOURCE_GROUP: portfolio-rg
  LOCATION: eastus
  ACR_NAME: portfolioacr${{ secrets.ACR_UNIQUE_SUFFIX }} 
  CONTAINER_ENV_NAME: portfolio-env
  API_APP_NAME: portfolio-api
  API_IMAGE_REPO: personal-portfolio-api
  API_PORT: 8080

jobs:
  api-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure Resource Group
        run: |
          az group create -n $RESOURCE_GROUP -l $LOCATION

      - name: Ensure Container Apps Environment
        run: |
          if ! az containerapp env show -n $CONTAINER_ENV_NAME -g $RESOURCE_GROUP >/dev/null 2>&1; then
            az containerapp env create -n $CONTAINER_ENV_NAME -g $RESOURCE_GROUP -l $LOCATION
          fi

      - name: Ensure ACR
        run: |
          if ! az acr show -n $ACR_NAME >/dev/null 2>&1; then
            az acr create -n $ACR_NAME -g $RESOURCE_GROUP --sku Basic --admin-enabled false
          fi
          az acr login -n $ACR_NAME
          LOGIN_SERVER=$(az acr show -n $ACR_NAME --query loginServer -o tsv)
          echo "LOGIN_SERVER=$LOGIN_SERVER" >> $GITHUB_ENV

      - name: Build API Image
        run: |
          docker build -t $LOGIN_SERVER/$API_IMAGE_REPO:${GITHUB_SHA} -f Server/Dockerfile --target final-no-frontend .

      - name: Push API Image
        run: |
          docker push $LOGIN_SERVER/$API_IMAGE_REPO:${GITHUB_SHA}

      - name: Deploy / Update API Container App
        run: |
          set -e
          IMAGE_REF="$LOGIN_SERVER/$API_IMAGE_REPO:${GITHUB_SHA}"
          SHORT_SHA=${GITHUB_SHA:0:7}
          echo "Preparing deployment for image: $IMAGE_REF"
          ACR_ID=$(az acr show -n $ACR_NAME --query id -o tsv)
          FALLBACK=false

          if az containerapp show -n $API_APP_NAME -g $RESOURCE_GROUP >/dev/null 2>&1; then
            echo "Container App exists. Ensuring system identity & AcrPull role."
            PRINCIPAL_ID=$(az containerapp show -n $API_APP_NAME -g $RESOURCE_GROUP --query identity.principalId -o tsv || true)
            if [ -z "$PRINCIPAL_ID" ] || [ "$PRINCIPAL_ID" = "null" ]; then
              echo "Assigning system identity..."
              az containerapp update -n $API_APP_NAME -g $RESOURCE_GROUP --identity system >/dev/null
              PRINCIPAL_ID=$(az containerapp show -n $API_APP_NAME -g $RESOURCE_GROUP --query identity.principalId -o tsv)
            fi
            echo "App principalId: $PRINCIPAL_ID"
            echo "Attempting AcrPull role assignment..."
            if az role assignment create --role AcrPull --assignee $PRINCIPAL_ID --scope $ACR_ID >/dev/null 2>&1; then
              echo "AcrPull granted. Updating to private image using system identity."
              az containerapp registry set -n $API_APP_NAME -g $RESOURCE_GROUP --server $LOGIN_SERVER --identity system >/dev/null
              az containerapp update \
                -n $API_APP_NAME -g $RESOURCE_GROUP \
                --image $IMAGE_REF \
                --revision-suffix "rev-$SHORT_SHA" \
                --set-env-vars ASPNETCORE_ENVIRONMENT=Production \
                --cpu 0.5 --memory 1Gi
            else
              echo "WARNING: Role assignment failed (insufficient RBAC?). Will use admin credential fallback." >&2
              FALLBACK=true
            fi
          else
            echo "Creating app with public placeholder image + system identity first."
            az containerapp create \
              -n $API_APP_NAME -g $RESOURCE_GROUP -l $LOCATION \
              --environment $CONTAINER_ENV_NAME \
              --image mcr.microsoft.com/azuredocs/containerapps-helloworld:latest \
              --ingress external --target-port $API_PORT \
              --revision-suffix "rev-init" \
              --set-env-vars ASPNETCORE_ENVIRONMENT=Production \
              --cpu 0.5 --memory 1Gi \
              --identity system
            PRINCIPAL_ID=$(az containerapp show -n $API_APP_NAME -g $RESOURCE_GROUP --query identity.principalId -o tsv)
            echo "App principalId: $PRINCIPAL_ID"
            echo "Assigning AcrPull to new app principal..."
            if az role assignment create --role AcrPull --assignee $PRINCIPAL_ID --scope $ACR_ID >/dev/null 2>&1; then
              echo "Role assignment succeeded. Updating to private image."
              az containerapp registry set -n $API_APP_NAME -g $RESOURCE_GROUP --server $LOGIN_SERVER --identity system >/dev/null
              az containerapp update \
                -n $API_APP_NAME -g $RESOURCE_GROUP \
                --image $IMAGE_REF \
                --revision-suffix "rev-$SHORT_SHA" \
                --set-env-vars ASPNETCORE_ENVIRONMENT=Production \
                --cpu 0.5 --memory 1Gi
            else
              echo "WARNING: Role assignment failed. Will fallback to admin credentials." >&2
              FALLBACK=true
            fi
          fi

          if [ "$FALLBACK" = true ]; then
            echo "Enabling ACR admin user (temporary fallback)." >&2
            az acr update -n $ACR_NAME --admin-enabled true >/dev/null
            ACR_USER=$(az acr credential show -n $ACR_NAME --query username -o tsv)
            ACR_PASS=$(az acr credential show -n $ACR_NAME --query 'passwords[0].value' -o tsv)
            echo "Configuring registry credentials on Container App."
            if az containerapp show -n $API_APP_NAME -g $RESOURCE_GROUP >/dev/null 2>&1; then
              az containerapp registry set -n $API_APP_NAME -g $RESOURCE_GROUP --server $LOGIN_SERVER --username $ACR_USER --password $ACR_PASS >/dev/null
              az containerapp update -n $API_APP_NAME -g $RESOURCE_GROUP \
                --image $IMAGE_REF --revision-suffix "rev-$SHORT_SHA" \
                --set-env-vars ASPNETCORE_ENVIRONMENT=Production \
                --cpu 0.5 --memory 1Gi
            else
              az containerapp create -n $API_APP_NAME -g $RESOURCE_GROUP -l $LOCATION \
                --environment $CONTAINER_ENV_NAME --image $IMAGE_REF \
                --ingress external --target-port $API_PORT \
                --revision-suffix "rev-$SHORT_SHA" \
                --set-env-vars ASPNETCORE_ENVIRONMENT=Production \
                --cpu 0.5 --memory 1Gi \
                --registry-server $LOGIN_SERVER --registry-username $ACR_USER --registry-password $ACR_PASS
            fi  ;
          fi

          API_FQDN=$(az containerapp show -n $API_APP_NAME -g $RESOURCE_GROUP --query properties.configuration.ingress.fqdn -o tsv)
          echo "API_FQDN=$API_FQDN" >> $GITHUB_ENV
          echo "Deployed API FQDN: https://$API_FQDN"

      - name: Summary
        run: |
          echo "API deployed at: https://$API_FQDN"
